### ISSUE TITLE
Possible typo in version statements

### ISSUE THREAD

**Issue by WebFreak001** [das-developers/das2D#2]
https://github.com/das-developers/das2D/blob/2a3bc8ce9e6230c2c02229a326b5fea652556f0c/das2/stream.d#L186

I think this (and 2 other occurrences) were actually supposed to be `version (BigEndian)`?

**Comment by cpiker** [comment]
Thanks!  In the future I'll branch on `version (LittleEndian)` since that's more likely to be noticed during development.
